name: Packer CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  packer-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packer/imageBuilding

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"        

      - name: Initialize Packer
        run: packer init .


      - name: Format Packer template
        run: packer fmt -check -recursive .

      - name: Decode Variable File
        run: |
          echo "${{ secrets.PACKER_VAR_FILE_BASE64 }}" | base64 --decode > variables.auto.pkvars.hcl       

      - name: Decode public key
        run: |
          echo "${{ secrets.PACKER_PUB_KEY_BASE64 }}" | base64 --decode > tf-packer.pub     

      - name: Setup Environment Variable
        run: echo "PKR_VAR_image_name=web-app-image-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV  

      - name: Print Environment Variable
        run: echo $PKR_VAR_image_name
        
      - name: Validate Packer template
        run: packer validate -var-file=./variables.auto.pkvars.hcl . 
