name: Rolling Update
# on:
#   workflow_run:
#     workflows: [packer_image_build]
#     types:
#       - completed

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Authorize GCP
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ secrets.GCP_CLOUD_USER_SA }}    

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: ">= 363.0.0"
        project_id: ${{ secrets.GCP_CLOUD_USER_SA.project_id }}

    - name: Generating env variables
      run: |
        echo "UNIQUE_TEMPLATE_NAME=webapp-template-$(date +%s)" >> $GITHUB_ENV 
        echo "REGION=us-east1" >> $GITHUB_ENV                

    - name: Create a new Instance Template
      id: create-instance-template
      run: |
        gcloud compute instance-templates create $UNIQUE_TEMPLATE_NAME \
        --instance-template-region="${{ env.REGION }}" \
        --machine-type="e2-medium" \
        --image="web-app-image-20240327185559" \
        --boot-disk-device-name="persistent-disk-0" \
        --boot-disk-size="100GB" \
        --boot-disk-type="pd-standard" \
        --metadata=startup-script="#!/bin/bash
        touch /opt/webapp/.env.production
        : > /opt/webapp/.env.production
        cat > /opt/webapp/.env.production <<-INNER_EOF
        PORT=\"3000\"
        # DATABASE
        DB_TYPE=\"postgres\"
        DB_HOST=\"10.31.0.2\"
        DB_PORT=5432
        DB_USERNAME=\"webapp\"
        DB_PASSWORD=\"NELuXPfauDfi2QT6\"
        DB_NAME=\"webapp\"
        # Pub/Sub
        USER_CREATED_TOPC=\"user-created\"
        EMAIL_VALIDITY_MINUTES=\"1\"" \
        --network-tier="STANDARD" \
        --maintenance-policy="MIGRATE" \
        --provisioning-model="STANDARD" \
        --network="https://www.googleapis.com/compute/v1/projects/cloud-dev-project-417513/global/networks/vpc-1" \
        --subnet="https://www.googleapis.com/compute/v1/projects/cloud-dev-project-417513/regions/${{ env.REGION }}/subnetworks/webapp" \
        --tags="load-balanced-backend" \
        --service-account="compute-service-account@cloud-dev-project-417513.iam.gserviceaccount.com" \
        --scopes="cloud-platform"

    - name: Update Managed Instance Group with new template
      id: update-mig
      run: |
        gcloud compute instance-groups managed set-instance-template \
        l7-xlb-backend-example \
        --template=projects/cloud-dev-project-417513/regions/${{ env.REGION }}/instanceTemplates/$UNIQUE_TEMPLATE_NAME \
        --region=${{ env.REGION }}  

    - name: Trigger Rolling Update
      id: rolling-update-trigger
      run: |
        gcloud compute instance-groups managed rolling-action start-update \
        l7-xlb-backend-example \
        --version='template=projects/cloud-dev-project-417513/regions/${{ env.REGION }}/instanceTemplates/${{ env.UNIQUE_TEMPLATE_NAME }}' \
        --region=${{ env.REGION }} --max-surge=3

    - name: Wait for Rolling Update to completed
      id: wait-for-version-target-reached
      run: |
        gcloud compute instance-groups managed wait-until l7-xlb-backend-example --version-target-reached --region=${{ env.REGION }}
